<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Login | XYZ Transport</title>
<style>
*{box-sizing:border-box}html,body{width:100%;height:100%;margin:0}body{font-family:Arial,Helvetica,sans-serif;background:radial-gradient(circle at top left,rgba(22,163,74,.10),transparent 35%),#f4f7f5;color:#17201a}button,input{font:inherit}.page{min-height:100%;display:flex}.brand-panel{width:54%;background:#13351f;color:#fff;display:flex;align-items:center;justify-content:center;padding:60px}.brand-content{max-width:560px;width:100%}.brand-mark{width:58px;height:58px;display:flex;align-items:center;justify-content:center;background:#fff;color:#13351f;border-radius:12px;font-size:24px;font-weight:700;margin-bottom:32px}.brand-content h1{margin:0;font-size:46px;line-height:1.08;letter-spacing:-1.5px}.brand-content p{margin:22px 0 0;max-width:470px;color:#cce0d1;font-size:17px;line-height:1.6}.feature-line{margin-top:42px;display:flex;gap:28px;color:#d8e8dc;font-size:13px}.login-panel{width:46%;display:flex;align-items:center;justify-content:center;padding:50px}.login-box{width:100%;max-width:410px}.login-box h2{margin:0;font-size:30px;letter-spacing:-.5px}.login-subtitle{margin:9px 0 34px;color:#69736c;font-size:14px}.alert{background:#fff1f1;color:#b42318;border:1px solid #ffc9c9;border-radius:7px;padding:11px 13px;margin-bottom:20px;font-size:13px}.field{margin-bottom:20px}.field label{display:block;margin-bottom:7px;font-size:13px;font-weight:700;color:#26352a}.field input{width:100%;height:46px;border:1px solid #cbd5cd;border-radius:7px;padding:0 14px;background:#fff;color:#17201a;outline:none}.field input:focus{border-color:#187a38;box-shadow:0 0 0 3px rgba(24,122,56,.12)}.remember-row{display:flex;align-items:center;margin:4px 0 25px;font-size:13px;color:#57615a}.remember-row input{margin:0 8px 0 0}.login-button{width:100%;height:47px;border:0;border-radius:7px;background:#176c33;color:#fff;font-weight:700;cursor:pointer}.login-button:hover{background:#125b2a}.keyboard-note{margin-top:18px;text-align:center;color:#7b857e;font-size:12px}kbd{display:inline-block;background:#fff;border:1px solid #cfd7d1;border-bottom-width:2px;border-radius:4px;padding:2px 6px;color:#39443c;font-size:11px}@media(max-width:900px){.brand-panel{display:none}.login-panel{width:100%}}
</style>
</head>
<body><div class="page"><section class="brand-panel"><div class="brand-content"><div class="brand-mark">XT</div><h1>Fast transport.<br>Faster entry.</h1><p>Excel-like voucher entry with proper customer, supplier, payment and outstanding tracking.</p><div class="feature-line"><span>Keyboard First</span><span>Fast Entry</span><span>Ledger Ready</span></div></div></section><main class="login-panel"><div class="login-box"><h2>Welcome back</h2><p class="login-subtitle">Sign in to continue to XYZ Transport.</p>@if($errors->any())<div class="alert">{{ $errors->first() }}</div>@endif<form method="POST" action="{{ route('login.attempt') }}">@csrf<div class="field"><label for="username">Username</label><input type="text" id="username" name="username" value="{{ old('username') }}" autocomplete="username" autofocus required></div><div class="field"><label for="password">Password</label><input type="password" id="password" name="password" autocomplete="current-password" required></div><label class="remember-row"><input type="checkbox" name="remember" value="1">Keep me signed in</label><button type="submit" class="login-button">Sign In</button></form><div class="keyboard-note">Enter username, press <kbd>Tab</kbd>, enter password and press <kbd>Enter</kbd></div></div></main></div></body></html>
