@extends('layouts.app')
@section('title','Customer Ledger | XYZ Transport')
@push('styles')@include('reports._styles')@endpush
@section('content')
<div class="app-workspace">
<div class="report-head no-print"><div class="title"><h1 class="text-xl font-black">Customer Ledger</h1><p class="text-sm text-slate-500">Customer freight, receipts and running outstanding.</p></div><form method="GET" class="report-filter"><label><span>Customer</span><select name="customer_id" data-slim-select data-placeholder="Select Customer"><option value="">Select Customer</option>@foreach($customers as $x)<option value="{{ $x->id }}" @selected($customer?->id===$x->id)>{{ $x->name }}</option>@endforeach</select></label><label><span>From</span><input type="date" name="from" value="{{ $from }}"></label><label><span>To</span><input type="date" name="to" value="{{ $to }}"></label><button class="report-btn primary">Show</button>@if($customer)<a class="report-btn inline-flex items-center" target="_blank" href="{{ route('reports.customer-statement',['customer'=>$customer,'from'=>$from,'to'=>$to]) }}">Print Statement</a>@endif</form></div>
@if(!$customer)<div class="report-panel p-10 text-center text-slate-400">Select a customer to view ledger.</div>@else
<div class="mb-2 flex flex-wrap items-center justify-between gap-2"><div><b>{{ $customer->name }}</b> <span class="text-sm text-slate-500">{{ $customer->phone }}</span></div><div class="text-sm font-bold">Opening: ₹{{ number_format($opening,2) }}</div></div>
<div class="report-panel overflow-auto"><table class="report-table"><thead><tr><th>Date</th><th>Particulars</th><th>Reference</th><th>Charge</th><th>Paid</th><th>Balance</th></tr></thead><tbody><tr class="bg-slate-50"><td>{{ \Carbon\Carbon::parse($from)->format('d-m-Y') }}</td><td class="font-bold">Opening Balance</td><td>-</td><td></td><td></td><td class="num font-black">₹{{ number_format($opening,2) }}</td></tr>@forelse($entries as $r)<tr><td>{{ \Carbon\Carbon::parse($r['date'])->format('d-m-Y') }}</td><td>{{ $r['particulars'] }}</td><td>{{ $r['reference']?:'-' }}</td><td class="num">{{ $r['charge']?('₹'.number_format($r['charge'],2)):'-' }}</td><td class="num">{{ $r['paid']?('₹'.number_format($r['paid'],2)):'-' }}</td><td class="num font-bold">₹{{ number_format($r['balance'],2) }}</td></tr>@empty<tr><td colspan="6" class="py-8 text-center text-slate-400">No transactions in this period.</td></tr>@endforelse</tbody></table></div>
<div class="report-summary"><div><small>Closing Outstanding</small><b class="{{ $closing>=0?'negative':'positive' }}">₹{{ number_format($closing,2) }}</b></div></div>
@endif</div>
@endsection
