@extends('layouts.app')
@section('title','Outstanding | XYZ Transport')
@push('styles')@include('reports._styles')@endpush
@section('content')
<div class="app-workspace"><div class="report-head"><div class="title"><h1 class="text-xl font-black">Outstanding</h1><p class="text-sm text-slate-500">Live customer receivable and supplier payable.</p></div><button type="button" onclick="window.print()" class="report-btn no-print">Print</button></div>
<div class="grid gap-5 xl:grid-cols-2">
<div><h2 class="mb-2 font-black text-slate-900">Customer Outstanding</h2><div class="report-panel overflow-auto"><table class="report-table"><thead><tr><th>Customer</th><th>Total Charges</th><th>Paid</th><th>Outstanding</th><th class="no-print">Action</th></tr></thead><tbody>@forelse($customerRows as $r)<tr><td><b>{{ $r['customer']->name }}</b><div class="text-xs text-slate-500">{{ $r['customer']->phone }}</div></td><td class="num">₹{{ number_format($r['charges'],2) }}</td><td class="num">₹{{ number_format($r['paid'],2) }}</td><td class="num font-black {{ $r['balance']>0?'negative':'positive' }}">₹{{ number_format($r['balance'],2) }}</td><td class="no-print"><a class="font-bold text-blue-700 underline" href="{{ route('reports.customer-ledger',['customer_id'=>$r['customer']->id]) }}">Ledger</a></td></tr>@empty<tr><td colspan="5" class="py-8 text-center text-slate-400">No customer outstanding.</td></tr>@endforelse</tbody></table></div></div>
<div><h2 class="mb-2 font-black text-slate-900">Supplier Outstanding</h2><div class="report-panel overflow-auto"><table class="report-table"><thead><tr><th>Supplier / Transporter</th><th>Freight</th><th>Advance + Paid</th><th>Payable</th><th class="no-print">Action</th></tr></thead><tbody>@forelse($supplierRows as $r)<tr><td><b>{{ $r['supplier']->name }}</b><div class="text-xs text-slate-500">{{ $r['supplier']->phone }}</div></td><td class="num">₹{{ number_format($r['freight'],2) }}</td><td class="num">₹{{ number_format($r['advance']+$r['paid'],2) }}</td><td class="num font-black {{ $r['balance']>0?'negative':'positive' }}">₹{{ number_format($r['balance'],2) }}</td><td class="no-print"><a class="font-bold text-blue-700 underline" href="{{ route('reports.supplier-ledger',['supplier_id'=>$r['supplier']->id]) }}">Ledger</a></td></tr>@empty<tr><td colspan="5" class="py-8 text-center text-slate-400">No supplier outstanding.</td></tr>@endforelse</tbody></table></div></div>
</div></div>
@endsection
