@extends('layouts.app')
@section('title','Profit Report | XYZ Transport')
@push('styles')@include('reports._styles')@endpush
@section('content')
<div class="app-workspace"><div class="report-head no-print"><div class="title"><h1 class="text-xl font-black">Profit Report</h1><p class="text-sm text-slate-500">Current approved rule: Customer Freight − Supplier Freight.</p></div><form method="GET" class="report-filter"><label><span>From</span><input type="date" name="from" value="{{ $filters['from'] }}"></label><label><span>To</span><input type="date" name="to" value="{{ $filters['to'] }}"></label><label><span>Transport</span><select name="transport_company_id" data-slim-select><option value="">All</option>@foreach($companies as $x)<option value="{{ $x->id }}" @selected($filters['transport_company_id']==$x->id)>{{ $x->name }}</option>@endforeach</select></label><label><span>Customer</span><select name="customer_id" data-slim-select><option value="">All</option>@foreach($customers as $x)<option value="{{ $x->id }}" @selected($filters['customer_id']==$x->id)>{{ $x->name }}</option>@endforeach</select></label><label><span>Supplier</span><select name="supplier_id" data-slim-select><option value="">All</option>@foreach($suppliers as $x)<option value="{{ $x->id }}" @selected($filters['supplier_id']==$x->id)>{{ $x->name }}</option>@endforeach</select></label><button class="report-btn primary">Show</button><button type="button" onclick="window.print()" class="report-btn">Print</button></form></div>
<div class="report-panel overflow-auto"><table class="report-table"><thead><tr><th>Sr</th><th>LR Date</th><th>Transport</th><th>LR No</th><th>Customer</th><th>Supplier</th><th>Route</th><th>Customer Freight</th><th>Supplier Freight</th><th>Hamali Loading</th><th>Hamali Unloading</th><th>Profit</th></tr></thead><tbody>@forelse($rows as $v)@php $p=(float)$v->customer_freight-(float)$v->supplier_freight;@endphp<tr><td>{{ $v->sr_no }}</td><td>{{ optional($v->lr_date)->format('d-m-Y') }}</td><td><b>{{ $v->transportCompany?->name }}</b></td><td>{{ $v->lr_no?:'-' }}</td><td>{{ $v->customer?->name }}</td><td>{{ $v->supplier?->name?:'-' }}</td><td>{{ $v->from_place?:'-' }} → {{ $v->to_place?:'-' }}</td><td class="num">₹{{ number_format((float)$v->customer_freight,2) }}</td><td class="num">₹{{ number_format((float)$v->supplier_freight,2) }}</td><td class="num">₹{{ number_format((float)$v->hamali_loading,2) }}</td><td class="num">₹{{ number_format((float)$v->hamali_unloading,2) }}</td><td class="num font-black {{ $p>=0?'positive':'negative' }}">₹{{ number_format($p,2) }}</td></tr>@empty<tr><td colspan="12" class="py-8 text-center text-slate-400">No vouchers found.</td></tr>@endforelse</tbody></table></div>
<div class="report-summary"><div><small>Customer Freight</small><b>₹{{ number_format($totals['customer_freight'],2) }}</b></div><div><small>Supplier Freight</small><b>₹{{ number_format($totals['supplier_freight'],2) }}</b></div><div><small>Hamali (Reference)</small><b>₹{{ number_format($totals['hamali_loading']+$totals['hamali_unloading'],2) }}</b></div><div><small>Profit</small><b class="{{ $totals['profit']>=0?'positive':'negative' }}">₹{{ number_format($totals['profit'],2) }}</b></div></div>
<div class="mt-2 text-xs font-semibold text-slate-500">Hamali and GST are displayed separately and are not deducted from Profit until the client confirms that business rule.</div>
</div>
@endsection
