@extends('layouts.app')
@section('title','Supplier Ledger | XYZ Transport')
@push('styles')@include('reports._styles')@endpush
@section('content')
<div class="app-workspace">
<div class="report-head no-print"><div class="title"><h1 class="text-xl font-black">Supplier Ledger</h1><p class="text-sm text-slate-500">Supplier freight, advance/installments and running payable.</p></div><form method="GET" class="report-filter"><label><span>Supplier</span><select name="supplier_id" data-slim-select data-placeholder="Select Supplier"><option value="">Select Supplier</option>@foreach($suppliers as $x)<option value="{{ $x->id }}" @selected($supplier?->id===$x->id)>{{ $x->name }}</option>@endforeach</select></label><label><span>From</span><input type="date" name="from" value="{{ $from }}"></label><label><span>To</span><input type="date" name="to" value="{{ $to }}"></label><button class="report-btn primary">Show</button>@if($supplier)<a class="report-btn inline-flex items-center" target="_blank" href="{{ route('reports.supplier-statement',['supplier'=>$supplier,'from'=>$from,'to'=>$to]) }}">Print Statement</a>@endif</form></div>
@if(!$supplier)<div class="report-panel p-10 text-center text-slate-400">Select a supplier / transporter to view ledger.</div>@else
<div class="mb-2 flex flex-wrap items-center justify-between gap-2"><div><b>{{ $supplier->name }}</b> <span class="text-sm text-slate-500">{{ $supplier->phone }}</span></div><div class="text-sm font-bold">Opening: ₹{{ number_format($opening,2) }}</div></div>
<div class="report-panel overflow-auto"><table class="report-table"><thead><tr><th>Date</th><th>Particulars</th><th>Reference</th><th>Freight</th><th>Paid</th><th>Balance</th></tr></thead><tbody><tr class="bg-slate-50"><td>{{ \Carbon\Carbon::parse($from)->format('d-m-Y') }}</td><td class="font-bold">Opening Balance</td><td>-</td><td></td><td></td><td class="num font-black">₹{{ number_format($opening,2) }}</td></tr>@forelse($entries as $r)<tr><td>{{ \Carbon\Carbon::parse($r['date'])->format('d-m-Y') }}</td><td>{{ $r['particulars'] }}</td><td>{{ $r['reference']?:'-' }}</td><td class="num">{{ $r['charge']?('₹'.number_format($r['charge'],2)):'-' }}</td><td class="num">{{ $r['paid']?('₹'.number_format($r['paid'],2)):'-' }}</td><td class="num font-bold">₹{{ number_format($r['balance'],2) }}</td></tr>@empty<tr><td colspan="6" class="py-8 text-center text-slate-400">No transactions in this period.</td></tr>@endforelse</tbody></table></div>
<div class="report-summary"><div><small>Closing Payable</small><b class="{{ $closing>0?'negative':'positive' }}">₹{{ number_format($closing,2) }}</b></div></div>
@endif</div>
@endsection
